### ISSUE TITLE
Answer Changing Tag NEW PARAMS FILE (ctsm51d154_2deg_GSWP3V1_hist)

### ISSUE THREAD

**Issue by slevis-lmwg** [NCAR/LMWG_dev#38]
**Description:**

For updating the [Answer Changing Tags wiki page](https://github.com/ESCOMP/CTSM/wiki/Answer-changing-tags). Previous one was #28.

Used script /glade/work/slevis/Answer_Changing_Tags/setup_run_answer_changing_tags.csh_dev145-154 to start the case. 
(Remove _dev145-154 from file name to run it.)

___
**Case directory:**
/glade/work/slevis/git_ctsm_tags/ctsm5.1.dev154/cime/scripts/ctsm51d154_2deg_GSWP3V1_hist

___
**Sandbox:**
/glade/work/slevis/git_ctsm_tags/ctsm5.1.dev154

 ___
**user_nl_ changes:**
Other than the usual user_nl mods for Answer Changing Tags:
```
 finidat = '/glade/campaign/cgd/tss/people/slevis/CLM5_restarts/ctsm51d145_2deg_GSWP3V1_hist.clm2.r.1989-01-01-00000.nc'
 use_init_interp = .true.
```
Note that the finidat used here originates in #28.
 ___
**SourceMods:**
The simulation failed at the year transition from 2001 to 2002. I have tried the following:
1) WORKED. In issue https://github.com/ESCOMP/CTSM/issues/2264 I explain this first fix as:
"remove the new if istcrop, as well as the endrun and just set z0m and displa to 0 for tiny htop."
2) FAILED. In the same issue, I explain the second fix [in this post](https://github.com/ESCOMP/CTSM/issues/2264#issuecomment-1828425441) and why [it failed](https://github.com/ESCOMP/CTSM/issues/2264#issuecomment-1832837394).
3) DONE same as (1) but with these [suggestions](https://github.com/ESCOMP/CTSM/pull/2271#issuecomment-1834117795) to set z0m = z0mg and run with DEBUG.
4) DONE same as (1) but reverting to the pre-dev154 default `z0param_method = 'ZengWang2007'`.

___
**Diagnostics:**
1 vs. previous answer-changing tag:
https://webext.cgd.ucar.edu/I20TR/ctsm51d154_2deg_GSWP3V1_hist/lnd/ctsm51d154_2deg_GSWP3V1_hist.1995_2014-ctsm51d145_2deg_GSWP3V1_hist.1995_2014/setsIndex.html

3 vs. 4: https://webext.cgd.ucar.edu//I20TR/ctsm51d154_2deg_GSWP3V1_hist/lnd/ctsm51d154_2deg_GSWP3V1_hist.1995_2014-ctsm51d154like156_2deg_GSWP3V1_hist.1995_2014/setsIndex.html
___
**Output:**
1) /glade/campaign/cgd/tss/people/slevis/ANSWER_CHANGING_TAGS/ctsm51d154_2deg_GSWP3V1_hist/iss38_opt1
3) /glade/campaign/cgd/tss/people/slevis/ANSWER_CHANGING_TAGS/ctsm51d154_2deg_GSWP3V1_hist
4) /glade/campaign/cgd/tss/people/slevis/ANSWER_CHANGING_TAGS/ctsm51d154like156_2deg_GSWP3V1_hist
___
**Contacts:**
@slevis-lmwg 
___
**Extra details:**
1850-1919 cycle GSWP3 1901-1920 data
1920-2014 use GSWP3 1901-2014 data

**Comment by slevis-lmwg** [comment]
I have posted diagnostics from this run. 
I have not looked though.

**Comment by olyson** [comment]
I think the decrease in sensible heat flux and increase in surface temperature (TG) in warm desert regions (e.g., Sahara) is consistent with the Meier paper results.  Caused by lower z0mg.
The z0mv of vegetation is generally increased in Meier, so given the availability of moisture in the tropics that is probably driving an increase in the latent heat flux in those regions, against generally consistent with Meier.
We ourselves actually never did a clean comparison of Meier against a control because of bugs we ran into and the discussion we had regarding zetamaxstable and the changes made there.  Our efforts were focused on sorting out those issues.  Now that Meier in the model has settled down, it might be worth doing a simulation as in #38 here but with Meier off,  all else being the same.  A comparison with the Meier paper results might be complicated by the fact that they put each pft on its own soil column, I'm not sure what effect that might have with respect to roughness results.

**Comment by wwieder** [comment]
seems like we can do a clean comparison with dev154 vs. 156, since the
later turns Meier off by default.

**Comment by slevis-lmwg** [comment]
Can do.

First, I have started #38 again with Keith's and Erik's [suggestions](https://github.com/ESCOMP/CTSM/pull/2271#issuecomment-1834117795).

**Comment by slevis-lmwg** [comment]
Easiest way to do the new run is to clone #38 and add to user_nl_clm: 
`z0param_method = 'ZengWang2007'`
...rather than starting from scratch by checking out dev156. I hope you're both ok with this choice.

**Comment by olyson** [comment]
Seems ok to me.

**Comment by slevis-lmwg** [comment]
Just posted new diags up top:
Comparing dev154 (Meier2022 on) to dev156 (Meier2022 off)
